# Generated by Django 5.0.1 on 2024-03-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='avatar',
            field=models.CharField(default='/var/www/avatar/default.png', max_length=120),
        ),
    ]
