# Generated by Django 5.0.1 on 2024-03-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_login_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='avatar',
            field=models.CharField(default='/avatar/default/default.png', max_length=120),
        ),
    ]
