# Generated by Django 5.0.1 on 2024-03-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_login',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
