# Generated by Django 5.0.1 on 2024-03-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_login_loses_user_login_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='avatar',
            field=models.CharField(default='/avatar/default.png', max_length=120),
        ),
    ]
