"""
Django settings for transcendence project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

import pathlib, os, sys, json, aiohttp
import logging.config

logger = logging.getLogger("auth")  # __name__ is a common choice

logging.basicConfig(level="INFO")

try:
    with open("/secrets/logger_secrets.json") as fd:
        params_logger = json.load(fd)
    with open("/secrets/postgres_db_secrets.json") as fd:
        params_db = json.load(fd)
    with open("/secrets/jwt_secrets.json") as fd:
        params_jwt = json.load(fd)
    with open("/secrets/login_google_secrets.json") as fd:
        params_google_login = json.load(fd)
    with open("/secrets/login_intra_secrets.json") as fd:
        params_intra_login = json.load(fd)
except FileNotFoundError as err:
    logger.error(f"Error: Params File Not Found {err}")
    sys.exit(1)


LOGGER = params_logger["data"]["data"]
POSTGRES = params_db["data"]["data"]
JWT = params_jwt["data"]["data"]
GOOGLE = params_google_login["data"]["data"]
INTRA = params_intra_login["data"]["data"]

#Config with tools on vault
LOGGER["handlers"]["file"]["filename"] = "/log/gateway.log"
logging.config.dictConfig(LOGGER)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%fmk_ra(3@i6m+cto&6b$&5m!x)%1eyp#qrku=_6&*@w9a)@j='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['trascendence.tech', 'www.trascendence.tech','65.109.174.85','195.35.48.173','auth', 'localhost', 'login', 'https://localhost', 'trascendence.tech', 'gateway']


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'transcendence.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'transcendence.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': POSTGRES['POSTGRES_DB'],
        'HOST': POSTGRES['POSTGRES_HOST'],
        'USER': POSTGRES['POSTGRES_USER'],
        'PASSWORD': POSTGRES['POSTGRES_PASSWORD']
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://65.109.174.85:8080",
    "http://65.109.174.85:25671",
    "http://65.109.174.85",
    "http://trascendence.tech",
    "https://trascendence.tech",
    "http://localhost:8080",
    "https://localhost:8080",
    "http://localhost:25671",
    "https://localhost:25671",
    "http://localhost",
    "https://localhost"
]

CORS_ALLOW_CREDENTIALS = True
