# Generated by Django 5.0.1 on 2024-03-30 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_friends_status_alter_friends_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_matches', to='user.user_login')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_matches', to='user.user_login')),
            ],
            options={
                'db_table': 'user_matches',
            },
        ),
    ]
