# Generated by Django 5.0.1 on 2024-03-30 22:54

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_matchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='p1_score',
            field=models.SmallIntegerField(default=0, verbose_name=user.models.user_login),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='p2_score',
            field=models.SmallIntegerField(default=0, verbose_name=user.models.user_login),
            preserve_default=False,
        ),
    ]
