# Generated by Django 5.0.1 on 2024-05-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_matchhistory_p1_score_matchhistory_p2_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='challenge',
            field=models.SmallIntegerField(default=0),
        ),
    ]
