# Generated by Django 5.0.1 on 2024-01-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_login',
            },
        ),
    ]
