# Generated by Django 5.0.1 on 2024-01-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_login_user_username_user_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('email', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'user_login',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
