# Generated by Django 5.0.1 on 2024-02-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_login_last_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='email',
            field=models.EmailField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='last_log',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
