# Generated by Django 5.0.1 on 2024-02-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_login_email_alter_user_login_last_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='mode',
            field=models.SmallIntegerField(default=0),
        ),
    ]
