"""
Django settings for transcendence project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os, json, sys, pathlib
import logging.config
import logging.handlers

logger = logging.getLogger("login")  # __name__ is a common choice

logging.basicConfig(level="INFO")

try:
    with open("/secrets/login_intra_secrets.json") as fd:
        params_intra_login = json.load(fd)
    with open("/secrets/login_google_secrets.json") as fd:
        params_google_login = json.load(fd)
    with open("/secrets/login_google_secrets.json") as fd:
        params_login_google = json.load(fd)
    with open("/secrets/server_secrets.json") as fd:
        params_server = json.load(fd)
    with open("/secrets/logger_secrets.json") as fd:
        params_logger = json.load(fd)
    with open("/secrets/postgres_db_secrets.json") as fd:
        params_db = json.load(fd)
except FileNotFoundError as err:
    logger.error(f"Error: Params File Not Found {err}")
    sys.exit(1)

LOGGER = params_logger["data"]["data"]
INTRA = params_intra_login["data"]["data"]
GOOGLE = params_google_login["data"]["data"]
TRANSCENDENCE = params_server["data"]["data"]
POSTGRES = params_db["data"]["data"]

#Config with tools on vault
LOGGER["handlers"]["file"]["filename"] = "/log/login.log"
logging.config.dictConfig(LOGGER)

logger.warning(f"GOOGLE: {GOOGLE}")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


FRONTEND_BASE_URL = 'http://localhost:8080'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!41*+ai(5cgxamj&(zt6n5tp10kqw-&6=$*tu%!y-+_6#c4&k('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["65.109.174.85","localhost","195.35.48.173","trascendence.tech","login"]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'login.apps.LoginConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'transcendence.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'transcendence.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': POSTGRES['POSTGRES_DB'],
        'HOST': POSTGRES['POSTGRES_HOST'],
        'USER': POSTGRES['POSTGRES_USER'],
        'PASSWORD': POSTGRES['POSTGRES_PASSWORD']
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://65.109.174.85:8080",
    "http://65.109.174.85:25671",
    "http://65.109.174.85",
    "https://trascendence.tech",
    "http://localhost:8080",
    "https://localhost:8080",
    "http://localhost:25671",
    "https://localhost:25671",
    "http://localhost",
    "https://localhost"
]

CORS_ALLOW_CREDENTIALS = True

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "kv",
    }
}